apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "app-chart.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /otusapp($|/)(.*)
            backend:
              serviceName: {{ include "app-chart.fullname" . }}
              servicePort: 9000
