app:
  version: 4.0.1
  image-user: gorasu/task4:4.0.2

metrics:
  serviceMonitor:
    enabled: true

mysql:
  master:
    persistence:
      size: 8Gi
  image:
    tag: 5.7.27
  db:
    name: "myapp"
    user: "admin"
    password: "112233"
  replication:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
        enabled: true
        interval: 10s
        namespace: "default"
