app:
  version: 0.0.2
  image: gorasu/usecase:0.0.2
  redis: redis://usecase-chart-redis.default.svc.cluster.local:6379



metrics:
  serviceMonitor:
    enabled: true

mysql:
  master:
    persistence:
      size: 8Gi
  image:
    tag: 5.7.27
  db:
    name: "myapp"
    user: "admin"
    password: "112233"
    rootUser:
      password: "3232kwp2o3k32pokw32pw039iw03209iiw092j9032js3"
  replication:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
        enabled: true
        interval: 10s
        namespace: "default"
