app:
  version: 0.0.1
  image: gorasu/usecase:0.1.1
  redis: redis://usecase-chart-redis.default.svc.cluster.local:6379
  authService: http://auth-app-chart.default.svc.cluster.local:9000


metrics:
  serviceMonitor:
    enabled: true

mysql:
  master:
    persistence:
      size: 8Gi
  image:
    tag: 5.7.27
  root:
    password: "dewdijewodijewiodj32423423342"
  db:
    name: "usecase"
    user: "admin"
    password: "112233"
  replication:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
        enabled: true
        interval: 10s
        namespace: "default"
