apiVersion: skaffold/v2beta2
kind: Config
build:

deploy:
  helm:
    releases:
      - name: usecase-chart
        chartPath: usecase-chart
        setValues:
          app.redis: redis://usecase-chart-redis.default.svc.cluster.local:6379
