apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "usecase.fullname" . }}
spec:
  completions: 1
  template:
    metadata:
      name: {{ include "usecase.fullname" . }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: post-install-job
          envFrom:
              - configMapRef:
                  name: {{ include "usecase.fullname" . }}
          image: {{ .Values.app.image }}
          command:
            - sh
            - "-c"
            - |
              cd ../ && php bin/console doctrine:migrations:migrate -n --env=prod
