apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "auth.fullname" . }}-user
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "{{ .Values.app.authService }}/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/auth/login"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-User,X-Email,X-UserId,X-First-Name,X-Last-Name"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /users/(me)
            backend:
              serviceName: {{ include "auth.fullname" . }}
              servicePort: 9000
