apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth.fullname" . }}
  labels:
    {{ include "auth.labels" .  | nindent 4 }}
    proms: {{ include "auth.fullname" . }}-service
spec:
  selector:
     {{ include "auth.labels" .  | nindent 4 }}
  ports:
    - protocol: TCP
      port: 9000
      targetPort: http
      name: web
  type: NodePort
