apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "usecase.fullname" . }}-redis
  labels:
  {{ include "usecase.labels" .  | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ include "usecase.labels" .  | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
      {{ include "usecase.labels" . | nindent 8  }}
    spec:
      containers:
        - name: master
          image: "redis:alpine"  # or just image: redis
          ports:
            - name: redis
              containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "usecase.fullname" . }}-redis
  labels:
    {{ include "usecase.labels" .  | nindent 4 }}
spec:
  selector:
  {{ include "usecase.labels" .  | nindent 4 }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: redis
      name: redis-service
  type: NodePort